### ISSUE TITLE
Subclassing OcTreeNode - memory bug

### ISSUE THREAD

**Issue by leftys** [OctoMap/octomap#93] opened 2015-11-01 10:23 UTC
Hello!

I tried to subclass OcTreeNode and add new variables into the class. Unfortunately, OccupancyOcTreeBase.hxx called node's expandNode(), which called createChild implemented in  OcTreeDataNode and not in my subclass. However, createChild allocates memory for wrong data type:
```children[i] = new OcTreeDataNode<float>();```.

This led to SIGSEGV crashes. I made a work-around by implementing expandNode() in my subclass. Is it a bug? Or is there any recommended way to deal with it? The short advice in OcTreeNode class is apparently wrong:
>   * Hint: If a class is derived from OcTreeNode, you have to implement (at least) 
>   * createChild, getChild, and getChild const

**Comment by ahornung** [comment] 2015-11-07 19:45
Do you have a link to example code?

Which is the exact type of your Octree class, how is it derived from OccupancyOcTreeBase?

ColorOcTree (+its node class) is a good example for a derived octree structure, it's also implementing expandNode(). If I understood you correctly then it's working as intended when you also implement expandNode() in your Node class? If you added new variables to the node then I think it's a good idea to specialize expandNode anyways, to fill these values from the parent node.

**Comment by ahornung** [comment] 2015-12-29 21:25
I can confirm that you currently have to implement expandNode() when adding new members to octree nodes, so I'm closing here. Please check out issue #98 for a discussion of possible improvements.

**Closed by ahornung** 2015-12-29 21:25 UTC
