### ISSUE TITLE
octovis cannot open files

### ISSUE THREAD

**Issue by jlsv888** [OctoMap/octomap#365] opened 2022-03-18 10:58 UTC
I just installed octomap and octovis and I cannot open any files (I get an empty window).

![Screenshot from 2022-03-18 05-32-40](https://user-images.githubusercontent.com/101869304/158988869-3634797c-912f-4a3c-bdc6-80957a413bd0.png)

Here is my system info:
ubuntu 18.04
cmake version 3.22.1
gcc 9.4.0
QMake version 2.01a / Qt version 4.8.7 
libQGLViewer 2.6.3

My installation was the following 
cmake .. -DOCTOVIS_QT5=OFF

I got this warning:
CMake Warning (dev) at /usr/local/share/cmake-3.22/Modules/FindOpenGL.cmake:315 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  octovis/CMakeLists.txt:71 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

I did not have any issues on the build and install steps.

**Comment by tengfoonglam** [comment] 2022-05-23 20:38
Hello, I was wondering if have you tried running with sudo? `sudo octovis`

**Comment by RyanWagner10000** [comment] 2022-06-08 17:59
Hey, I was having a very similar problem but running "sudo octovis" worked for me. Thank you!

**Comment by igricart** [comment] 2023-01-19 11:23
In case you get `octovis: command not found`, try using the whole path as `/opt/ros/noetic/bin/octovis` for example.

**Comment by jlsv888** [comment] 2023-01-19 11:31
thanks all! using sudo octovis worked

**Comment by whoenig** [comment] 2024-03-13 08:49
potentially related to https://github.com/OctoMap/octomap/pull/414

**Comment by ahornung** [comment] 2024-03-17 21:47
Closing for now - should be fixed with the latest update (though I couldn't reproduce it myself with my own Ubuntu installation).

**Closed by ahornung** 2024-03-17 21:47 UTC
Labels: octovis
