### ISSUE TITLE
Octovis compilation error

### ISSUE THREAD

**Issue by jaychak** [OctoMap/octomap#73] opened 2014-11-26 04:24 UTC
I am on Ubuntu 12.04 LTS, and have libqt4-dev, libqt4-opengl-dev and libqglviewer-qt4-dev already installed.

I compiled Octomap successfully, but during compilation of Octovis (using CMake),
I get the following errors:

~/Documents/octomap-devel/octovis/build$ make
Scanning dependencies of target octovis-shared
[  2%] Building CXX object CMakeFiles/octovis-shared.dir/src/SceneObject.cpp.o
[  5%] Building CXX object CMakeFiles/octovis-shared.dir/src/PointcloudDrawer.cpp.o
[  8%] Building CXX object CMakeFiles/octovis-shared.dir/src/OcTreeDrawer.cpp.o
[ 10%] Building CXX object CMakeFiles/octovis-shared.dir/src/SelectionBox.cpp.o
[ 13%] Building CXX object CMakeFiles/octovis-shared.dir/src/TrajectoryDrawer.cpp.o
[ 16%] Building CXX object CMakeFiles/octovis-shared.dir/src/ColorOcTreeDrawer.cpp.o
Linking CXX shared library ../lib/liboctovis.so
[ 16%] Built target octovis-shared
[ 18%] Generating qrc_icons.cxx
[ 21%] Generating ui_ViewerGui.h
[ 24%] Generating ui_ViewerSettings.h
[ 27%] Generating ui_ViewerSettingsPanel.h
[ 29%] Generating ui_ViewerSettingsPanelCamera.h
[ 32%] Generating include/octovis/moc_ViewerGui.cxx
[ 35%] Generating include/octovis/moc_ViewerWidget.cxx
[ 37%] Generating include/octovis/moc_ViewerSettings.cxx
[ 40%] Generating include/octovis/moc_ViewerSettingsPanel.cxx
[ 43%] Generating include/octovis/moc_ViewerSettingsPanelCamera.cxx
[ 45%] Generating include/octovis/moc_CameraFollowMode.cxx
Scanning dependencies of target octovis
[ 48%] Building CXX object CMakeFiles/octovis.dir/src/main.cpp.o
In file included from /usr/include/qt4/QtCore/QtCore:79:0,
                 from /usr/include/qt4/QtGui/QtGui:3,
                 from /home/jay/Documents/octomap-devel/octovis/src/main.cpp:25:
/usr/include/qt4/QtCore/qtconcurrentfilter.h: In function ‘QtConcurrent::ThreadEngineStarter<void> QtConcurrent::filterInternal(Sequence&, KeepFunctor, ReduceFunctor)’:
/usr/include/qt4/QtCore/qtconcurrentfilter.h:108:47: warning: typedef ‘Iterator’ locally defined but not used [-Wunused-local-typedefs]
     typedef typename Sequence::const_iterator Iterator;
                                               ^
[ 51%] Building CXX object CMakeFiles/octovis.dir/src/ViewerGui.cpp.o
[ 54%] Building CXX object CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o
[ 56%] Building CXX object CMakeFiles/octovis.dir/src/ViewerSettings.cpp.o
[ 59%] Building CXX object CMakeFiles/octovis.dir/src/ViewerSettingsPanel.cpp.o
[ 62%] Building CXX object CMakeFiles/octovis.dir/src/ViewerSettingsPanelCamera.cpp.o
[ 64%] Building CXX object CMakeFiles/octovis.dir/src/CameraFollowMode.cpp.o
[ 67%] Building CXX object CMakeFiles/octovis.dir/include/octovis/moc_ViewerGui.cxx.o
[ 70%] Building CXX object CMakeFiles/octovis.dir/include/octovis/moc_ViewerWidget.cxx.o
[ 72%] Building CXX object CMakeFiles/octovis.dir/include/octovis/moc_ViewerSettings.cxx.o
[ 75%] Building CXX object CMakeFiles/octovis.dir/include/octovis/moc_ViewerSettingsPanel.cxx.o
[ 78%] Building CXX object CMakeFiles/octovis.dir/include/octovis/moc_ViewerSettingsPanelCamera.cxx.o
[ 81%] Building CXX object CMakeFiles/octovis.dir/include/octovis/moc_CameraFollowMode.cxx.o
[ 83%] Building CXX object CMakeFiles/octovis.dir/qrc_icons.cxx.o
Linking CXX executable ../bin/octovis
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::setCamPosition(double, double, double, double, double, double)':
ViewerWidget.cpp:(.text+0xbf6): undefined reference to `qglviewer::Camera::setPosition(qglviewer::Vec const&)'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::jumpToCamFrame(int, int)':
ViewerWidget.cpp:(.text+0xe66): undefined reference to `qglviewer::Frame::position() const'
ViewerWidget.cpp:(.text+0xe72): undefined reference to `qglviewer::Camera::setPosition(qglviewer::Vec const&)'
CMakeFiles/octovis.dir/include/octovis/moc_ViewerWidget.cxx.o:(.data.rel.ro._ZTVN7octomap12ViewerWidgetE[_ZTVN7octomap12ViewerWidgetE]+0xd0): undefined reference to `QGLViewer::keyReleaseEvent(QKeyEvent*)'
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/octovis] Error 1
make[1]: *** [CMakeFiles/octovis.dir/all] Error 2
make: *** [all] Error 2

**Comment by ahornung** [comment] 2015-07-26 07:04
I'm closing this, cannot reproduce on my machine. Feel free to re-open with more information.

**Closed by ahornung** 2015-07-26 07:04 UTC
