### ISSUE TITLE
Root node size is 6553.6 when deleting all nodes

### ISSUE THREAD

**Issue by lsouchet** [OctoMap/octomap#106] opened 2016-01-27 13:10 UTC
Hello,
I encountered an issue when using an octree. I have a custom octree type that adds a 64bits timestamp to each nodes.
I have a routine that periodically iterates over the leaves and delete them if their timestamp is too old.
When all nodes are too old and then deleted, the tree keeps one node at the root whose size happens to be huge (6553.6 exactly, which happens to like oddly like 2^16 to the comma).
When inserting rays into the tree again, this node is expanded into a lot of nodes, leading to a big memory allocation.

A test is provided in [PR#105](https://github.com/OctoMap/octomap/pull/105).
Is my use case incorrect? If so, what would be the correct way to achieve the same goal?
What makes the size of the node to be 6553.6?

Thanks in advance!

**Comment by ahornung** [comment] 2016-01-28 19:54
The root node spans over the complete tree volume, which is 2^16 * resolution. When only a root node (or an inner node with no children) remains, it is considered a pruned node. A pruned node means that it represents the same information as eight identical children, which it can be expanded to.

Now that case should not happen in your scenario. I think one reason could be using the iterators over a tree while deleting nodes. Modifying the tree invalidates the iterators since the underlying tree structure changes.

When you delete a node and it's the last child you also need to delete the parent node. Otherwise the parent is considered to be pruned and can be expanded as needed by the next operation. You can have a look at [deleteNodeRecurs()](https://github.com/OctoMap/octomap/blob/node-subclassing-tree/octomap/include/octomap/OcTreeBaseImpl.hxx#L630) in the `node-subclassing-tree` branch as a (top-down) example.

**Comment by lsouchet** [comment] 2016-02-10 08:49
I remember that I checked the deleteNodeRecurs() when investigating my issue and even though the name sounded right to fix my issue, the signature didn't quite matched my needs.

I'll try and look at it in you dev branch.

Thanks!

**Comment by ahornung** [comment] 2016-07-14 18:55
Is this still happening with the latest version in `devel`? If not then I'm inclined to close the issue as I can't reproduce it.

**Closed** 2019-12-03 18:52 UTC
